set DB_HOST=DB_HOST
set DB_PORT=12432
set DB_USER=DB_USER
set DB_PWD=DB_PWD
set DB_NAME=DB_USER_db

set REDIS_HOST=DB_HOST
set REDIS_PORT=REDIS_PORT
set REDIS_PWD=REDIS_PWD
set REDIS_DB=6

set JWT_SECRET=JWT_SECRET
set HASH_SECRET=HASH_SECRET
set PROXY_HOST=PROXY_HOST
npm run dev