### test pxg
GET http://localhost:7758/exchange/get_eth_account?account_name=tbgjoin

###login
POST  http://localhost:7005/api/account/login
content-type: application/json

{
    "user_name":"13",
    "user_pwd":"121"
}


###register
POST  http://localhost:7005/api/account/register
content-type: application/json; charset=UTF-8

{
    "user_id":"asdfada2",
    "user_pwd":"123",
    "user_type":"admin",
    "user_nick_name":"nick_name2"
}

###update
PATCH  http://localhost:7005/data/sys_user?user_id=eq.asdfada2

{ "user_name":"test1"}

###update
PATCH  http://postgrest.qrcode.isecsp.com/sys_user?user_id=eq.asdfada2

{ "user_name":"test1"}



###get
GET  http://localhost:7005/data/sys_user


###getCaptcha
GET  http://localhost:7005/api/tool/get_captcha
content-type: application/json; charset=UTF-8

{
    "user_name":"asdfada2",
    "user_pwd":"123",
    "user_type":"admin",
    "user_nick_name":"nick_name2"
}

